In [1]:
!uv pip install -U transformers datasets accelerate torch scikit-learn pandas numpy

Using Python 3.12.13 environment at: /usr
Resolved 78 packages in 1.20s
Prepared 48 packages in 53.28s
Uninstalled 33 packages in 3.00s
Installed 48 packages in 981ms
 - aiohappyeyeballs==2.6.1
 + aiohappyeyeballs==2.6.2
 - certifi==2026.4.22
 + certifi==2026.5.20
 - click==8.3.3
 + click==8.4.0
 - cuda-bindings==12.9.4
 + cuda-bindings==13.2.0
 - cuda-pathfinder==1.5.3
 + cuda-pathfinder==1.5.4
 - cuda-toolkit==12.8.1
 + cuda-toolkit==13.0.2
 - datasets==4.0.0
 + datasets==4.8.5
 - dill==0.3.8
 + dill==0.4.1
 - fsspec==2025.3.0
 + fsspec==2026.2.0
 - hf-xet==1.4.3
 + hf-xet==1.5.0
 - huggingface-hub==1.11.0
 + huggingface-hub==1.15.0
 - idna==3.13
 + idna==3.15
 - markdown-it-py==4.0.0
 + markdown-it-py==4.2.0
 - multiprocess==0.70.16
 + multiprocess==0.70.19
 - numpy==2.0.2
 + numpy==2.4.6
 + nvidia-cublas==13.1.1.3
 + nvidia-cuda-cupti==13.0.85
 + nvidia-cuda-nvrtc==13.0.88
 + nvidia-cuda-runtime==13.0.96
 + nvidia-cudnn-cu13==9.20.0.48
 + nvidia-cufft==12.0.0.61
 + nvidia-cufile==1.15.1.6
 + nvidia-curand==10.4.0.35
 + nvidia-cusolver==12.0.4.66
 + nvidia-cusparse==12.6.3.3
 + nvidia-cusparselt-cu13==0.8.1
 + nvidia-nccl-cu13==2.29.7
 + nvidia-nvjitlink==13.0.88
 + nvidia-nvshmem-cu13==3.4.5
 + nvidia-nvtx==13.0.85
 - packaging==26.1
 + packaging==26.2
 - pandas==2.2.2
 + pandas==3.0.3
 - propcache==0.4.1
 + propcache==0.5.2
 - psutil==5.9.5
 + psutil==7.2.2
 - pyarrow==18.1.0
 + pyarrow==24.0.0
 - regex==2025.11.3
 + regex==2026.5.9
 - requests==2.32.4
 + requests==2.34.2
 - rich==13.9.4
 + rich==15.0.0
 - scikit-learn==1.6.1
 + scikit-learn==1.8.0
 - scipy==1.16.3
 + scipy==1.17.1
 - setuptools==75.2.0
 + setuptools==81.0.0
 - torch==2.10.0+cu128
 + torch==2.12.0
 - transformers==5.0.0
 + transformers==5.9.0
 - triton==3.6.0
 + triton==3.7.0
 - typer==0.24.2
 + typer==0.25.1
 - urllib3==2.5.0
 + urllib3==2.7.0
 - xxhash==3.6.0
 + xxhash==3.7.0
 - yarl==1.23.0
 + yarl==1.24.2

### Fix numpy version conflict

The previous `!uv pip install` command might have installed a `numpy` version (2.x) that is incompatible with `scipy` or `scikit-learn`, leading to the `AttributeError`. To fix this, we will explicitly install `numpy==1.26.4` and ensure `scipy` and `scikit-learn` are reinstalled to be compatible with this `numpy` version.

In [5]:
# Uninstall current numpy, scipy, and scikit-learn to prepare for specific version installation
!uv pip uninstall numpy scipy scikit-learn

# Install numpy==1.26.4 and reinstall scipy and scikit-learn to ensure compatibility
# uv will resolve compatible versions for scipy and scikit-learn with numpy==1.26.4
!uv pip install numpy==1.26.4 scipy scikit-learn

Using Python 3.12.13 environment at: /usr
Uninstalled 3 packages in 271ms
 - numpy==2.4.6
 - scikit-learn==1.8.0
 - scipy==1.17.1
Using Python 3.12.13 environment at: /usr
Resolved 5 packages in 147ms
Prepared 1 package in 477ms
Installed 3 packages in 132ms
 + numpy==1.26.4
 + scikit-learn==1.8.0
 + scipy==1.17.1

In [1]:
import torch
print(torch.cuda.is_available())

True

In [2]:
import pandas as pd
import numpy as np

df=pd.read_csv("final_fake_real_dataset.csv")

In [3]:
from sklearn.model_selection import train_test_split

# Load CSV
df = pd.read_csv("final_fake_real_dataset.csv")

# Check columns
print(df.head())
print(df.columns)

# Example: keep only text + labels columns
# Replace names if needed
# df = df[["text", "labels"]]

# Train test split
train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)

print(train_df.shape)
print(test_df.shape)

                                             article  label
0  World's most popular candy to be removed from ...      0
1                         Browse Congressional Bills      1
2                        Supreme Court Vacancy Video      1
3                             U.S. Imports & Exports      1
4  Dying 78 Year Old CIA Agent Admits To Killing ...      0
Index(['article', 'label'], dtype='str')
(844, 2)
(212, 2)

In [8]:
# First, uninstall to ensure a clean slate
!uv pip uninstall torch torchvision torchaudio transformers accelerate
!pip cache purge

# Install torch, torchvision, and torchaudio from the official PyTorch index
# This helps ensure compatibility between the libraries and their C++ extensions.
# Assuming CUDA 12.1, change cu121 to your specific CUDA version if different.
!uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

# Reinstall other necessary packages
!uv pip install transformers datasets accelerate scikit-learn pandas numpy

Using Python 3.12.13 environment at: /usr
Uninstalled 5 packages in 552ms
 - accelerate==1.13.0
 - torch==2.12.0
 - torchaudio==2.11.0
 - torchvision==0.27.0
 - transformers==5.9.0
WARNING: No matching packages
Files removed: 0
Using Python 3.12.13 environment at: /usr
Resolved 27 packages in 4.73s
Prepared 16 packages in 58.85s
Uninstalled 13 packages in 131ms
Installed 16 packages in 289ms
 - nvidia-cublas-cu12==12.8.4.1
 + nvidia-cublas-cu12==12.1.3.1
 - nvidia-cuda-cupti-cu12==12.8.90
 + nvidia-cuda-cupti-cu12==12.1.105
 - nvidia-cuda-nvrtc-cu12==12.8.93
 + nvidia-cuda-nvrtc-cu12==12.1.105
 - nvidia-cuda-runtime-cu12==12.8.90
 + nvidia-cuda-runtime-cu12==12.1.105
 - nvidia-cudnn-cu12==9.10.2.21
 + nvidia-cudnn-cu12==9.1.0.70
 - nvidia-cufft-cu12==11.3.3.83
 + nvidia-cufft-cu12==11.0.2.54
 - nvidia-curand-cu12==10.3.9.90
 + nvidia-curand-cu12==10.3.2.106
 - nvidia-cusolver-cu12==11.7.3.90
 + nvidia-cusolver-cu12==11.4.5.107
 - nvidia-cusparse-cu12==12.5.8.93
 + nvidia-cusparse-cu12==12.1.0.106
 - nvidia-nccl-cu12==2.27.5
 + nvidia-nccl-cu12==2.21.5
 - nvidia-nvtx-cu12==12.8.90
 + nvidia-nvtx-cu12==12.1.105
 - sympy==1.14.0
 + sympy==1.13.1
 + torch==2.5.1+cu121
 + torchaudio==2.5.1+cu121
 + torchvision==0.20.1+cu121
 - triton==3.7.0
 + triton==3.1.0
Using Python 3.12.13 environment at: /usr
Resolved 72 packages in 233ms
Installed 2 packages in 56ms
 + accelerate==1.13.0
 + transformers==5.9.0

In [4]:
import torch
import torchvision

print(torch.__version__)
print(torchvision.__version__)
print(torch.cuda.is_available())

2.5.1+cu121
0.20.1+cu121
True

In [5]:
# What your SimpleTransformers code is internally doing
# Rewritten using Hugging Face Transformers (recommended)

# Install if needed:
# pip install transformers datasets torch scikit-learn pandas

import pandas as pd
import numpy as np
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# ---------------------------------------------------
# Expected input format:
# train_df columns = ["text", "labels"]
# test_df columns  = ["text", "labels"]
# labels: 0 = Fake, 1 = Real (example)
# ---------------------------------------------------

# Example:
# train_df = pd.DataFrame({
#     "text": ["news one", "news two"],
#     "labels": [0,1]
# })

# Rename columns to match expected format
train_df = train_df.rename(columns={"article": "text", "label": "labels"})
test_df = test_df.rename(columns={"article": "text", "label": "labels"})

# Convert pandas -> Hugging Face Dataset
train_dataset = Dataset.from_pandas(train_df)
test_dataset  = Dataset.from_pandas(test_df)

# Load tokenizer (RoBERTa)
tokenizer = AutoTokenizer.from_pretrained("roberta-base")

# Tokenization
def tokenize_function(example):
    return tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

train_dataset = train_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

# Keep only needed columns
train_dataset = train_dataset.remove_columns(
    [col for col in train_dataset.column_names if col not in ["input_ids", "attention_mask", "labels"]]
)

test_dataset = test_dataset.remove_columns(
    [col for col in test_dataset.column_names if col not in ["input_ids", "attention_mask", "labels"]]
)

train_dataset.set_format("torch")
test_dataset.set_format("torch")

# Load model
model = AutoModelForSequenceClassification.from_pretrained(
    "roberta-base",
    num_labels=2
)

# Metrics (what eval_model gives)
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="binary"
    )

    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }

# Training settings
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs",
    logging_steps=50,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    weight_decay=0.01,
    load_best_model_at_end=True,
    report_to="none"
)

# Trainer = internally what simpletransformers uses conceptually
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

# Train model
trainer.train()

# Evaluate model
result = trainer.evaluate()

print(result)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Map:   0%|          | 0/212 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3672291040420532, 'eval_accuracy': 0.8867924528301887, 'eval_f1': 0.9083969465648855, 'eval_precision': 0.8686131386861314, 'eval_recall': 0.952}

In [10]:
import pandas as pd
import numpy as np
import torch

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

# ---------------------------------------------------
# 1. LOAD DATASET
# ---------------------------------------------------
df = pd.read_csv("final_fake_real_dataset.csv")

print("Columns:", df.columns)

# Rename columns automatically
rename_map = {
    "label": "labels",
    "Label": "labels",
    "class": "labels",
    "target": "labels",
    "news": "text",
    "content": "text",
    "article": "text",
    "headline": "text",
    "title": "text"
}

df = df.rename(columns=rename_map)

# Keep only required columns
df = df[["text", "labels"]]

df = df.dropna()
df["labels"] = df["labels"].astype(int)

# ---------------------------------------------------
# 2. TRAIN TEST SPLIT
# ---------------------------------------------------
train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["labels"]
)

# ---------------------------------------------------
# 3. METRICS FUNCTION
# ---------------------------------------------------
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="binary"
    )

    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

# ---------------------------------------------------
# 4. MODELS TO COMPARE
# ---------------------------------------------------
models = {
    "DistilBERT": "distilbert-base-uncased",
    "BERT": "bert-base-uncased",
    "RoBERTa": "roberta-base",
    "ALBERT": "albert-base-v2"
}

results = []

# ---------------------------------------------------
# 5. LOOP THROUGH MODELS
# ---------------------------------------------------
for model_name, model_checkpoint in models.items():

    print(f"\n========== Training {model_name} ==========\n")

    tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

    train_dataset = Dataset.from_pandas(train_df)
    test_dataset = Dataset.from_pandas(test_df)

    def tokenize_function(example):
        return tokenizer(
            example["text"],
            truncation=True,
            padding="max_length",
            max_length=256
        )

    train_dataset = train_dataset.map(tokenize_function, batched=True)
    test_dataset = test_dataset.map(tokenize_function, batched=True)

    train_dataset = train_dataset.remove_columns(
        [col for col in train_dataset.column_names if col not in ["input_ids", "attention_mask", "labels"]]
    )

    test_dataset = test_dataset.remove_columns(
        [col for col in test_dataset.column_names if col not in ["input_ids", "attention_mask", "labels"]]
    )

    train_dataset.set_format("torch")
    test_dataset.set_format("torch")

    model = AutoModelForSequenceClassification.from_pretrained(
        model_checkpoint,
        num_labels=2
    )

    training_args = TrainingArguments(
        output_dir=f"./{model_name}_results",
        eval_strategy="epoch",
        save_strategy="no",
        logging_steps=100,

        num_train_epochs=2,

        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,

        learning_rate=2e-5,
        weight_decay=0.01,

        fp16=torch.cuda.is_available(),

        report_to="none"
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        compute_metrics=compute_metrics
    )

    trainer.train()

    # Save the trained model
    trainer.save_model(f"./saved_{model_name}")

    result = trainer.evaluate()

    results.append({
        "Model": model_name,
        "Accuracy": result["eval_accuracy"],
        "Precision": result["eval_precision"],
        "Recall": result["eval_recall"],
        "F1 Score": result["eval_f1"]
    })

# ---------------------------------------------------
# 6. FINAL COMPARISON TABLE
# ---------------------------------------------------
results_df = pd.DataFrame(results)

print("\n================ FINAL RESULTS ================\n")
print(results_df.sort_values(by="Accuracy", ascending=False))

Columns: Index(['article', 'label'], dtype='str')

========== Training DistilBERT ==========

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Map:   0%|          | 0/212 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

========== Training BERT ==========

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Map:   0%|          | 0/212 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

========== Training RoBERTa ==========

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Map:   0%|          | 0/212 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

========== Training ALBERT ==========

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Map:   0%|          | 0/212 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/25 [00:00<?, ?it/s]

[transformers] AlbertForSequenceClassification LOAD REPORT from: albert-base-v2
Key                          | Status     |
-----------------------------+------------+-
predictions.dense.bias       | UNEXPECTED |
predictions.dense.weight     | UNEXPECTED |
predictions.LayerNorm.bias   | UNEXPECTED |
predictions.bias             | UNEXPECTED |
predictions.decoder.bias     | UNEXPECTED |
predictions.LayerNorm.weight | UNEXPECTED |
classifier.weight            | MISSING    |
classifier.bias              | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

================ FINAL RESULTS ================

        Model  Accuracy  Precision  Recall  F1 Score
2     RoBERTa  0.886792   0.897638   0.912  0.904762
1        BERT  0.872642   0.871212   0.920  0.894942
3      ALBERT  0.872642   0.860294   0.936  0.896552
0  DistilBERT  0.867925   0.859259   0.928  0.892308

In [7]:
# ======================================================
# SAVE ALL MODEL RESULTS TO CSV + EXCEL + TXT
# Add this AFTER your benchmarking code finishes
# ======================================================

import pandas as pd

# results list already created in your benchmark code
# Convert to DataFrame
results_df = pd.DataFrame(results)

# Sort by Accuracy
results_df = results_df.sort_values(by="Accuracy", ascending=False)

# ------------------------------------------
# 1. Save CSV
# ------------------------------------------
results_df.to_csv("model_comparison_results.csv", index=False)

# ------------------------------------------
# 2. Save Excel
# ------------------------------------------
results_df.to_excel("model_comparison_results.xlsx", index=False)

# ------------------------------------------
# 3. Save Text File
# ------------------------------------------
with open("model_comparison_results.txt", "w") as f:
    f.write(results_df.to_string(index=False))

# ------------------------------------------
# 4. Print Final Table
# ------------------------------------------
print(results_df)

print("\nFiles Saved Successfully:")
print("1. model_comparison_results.csv")
print("2. model_comparison_results.xlsx")
print("3. model_comparison_results.txt")

        Model  Accuracy  Precision  Recall  F1 Score
2     RoBERTa  0.886792   0.897638   0.912  0.904762
0  DistilBERT  0.877358   0.877863   0.920  0.898438
1        BERT  0.872642   0.871212   0.920  0.894942
3      ALBERT  0.872642   0.860294   0.936  0.896552

Files Saved Successfully:
1. model_comparison_results.csv
2. model_comparison_results.xlsx
3. model_comparison_results.txt

In [11]:
# ======================================================
# MULTI-MODEL BENCHMARK FOR FAKE NEWS DETECTION
# Train on one dataset and test on a NEW dataset
# Models:
# 1. DistilBERT
# 2. BERT-base
# 3. RoBERTa-base
# 4. ALBERT-base
# ======================================================

# pip install -U transformers datasets accelerate torch scikit-learn pandas numpy

import os
import pandas as pd
import numpy as np
import torch

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report
from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)


# ======================================================
# 7. TEST ON NEW DATASET
# ======================================================

new_df = pd.read_csv("new_test_dataset.csv")

print("\nNew test columns:", new_df.columns)

new_rename_map = {
    "label": "labels",
    "Label": "labels",
    "class": "labels",
    "target": "labels",
    "news": "text",
    "content": "text",
    "article": "text",
    "headline": "text",
    "title": "text"
}

new_df = new_df.rename(columns=new_rename_map)

# Keep only text and labels if labels exist
if "labels" in new_df.columns:
    new_df = new_df[["text", "labels"]]
    new_df = new_df.dropna()
    new_df["labels"] = new_df["labels"].astype(int)
else:
    new_df = new_df[["text"]].dropna()

new_results = []

for model_name, model_checkpoint in models.items():
    print(f"\n========== Testing {model_name} on NEW data ==========\n")

    save_path = f"./saved_{model_name}"

    tokenizer = AutoTokenizer.from_pretrained(save_path)
    model = AutoModelForSequenceClassification.from_pretrained(save_path)

    new_dataset = Dataset.from_pandas(new_df.reset_index(drop=True))

    def tokenize_new(example):
        return tokenizer(
            example["text"],
            truncation=True,
            padding="max_length",
            max_length=256
        )

    new_dataset = new_dataset.map(tokenize_new, batched=True)

    remove_cols_new = [c for c in new_dataset.column_names if c not in ["input_ids", "attention_mask", "labels"] and c != "text"]
    if "text" in new_dataset.column_names:
        remove_cols_new.append("text")

    # Remove only columns that exist
    remove_cols_new = [c for c in remove_cols_new if c in new_dataset.column_names]
    new_dataset = new_dataset.remove_columns(remove_cols_new)

    new_dataset.set_format("torch")

    new_trainer = Trainer(
        model=model,
        args=TrainingArguments(
            output_dir=f"./temp_{model_name}",
            per_device_eval_batch_size=16,
            report_to="none"
        )
    )

    preds_output = new_trainer.predict(new_dataset)
    logits = preds_output.predictions
    preds = np.argmax(logits, axis=1)

    if "labels" in new_df.columns:
        labels = np.array(new_df["labels"])

        acc = accuracy_score(labels, preds)
        precision, recall, f1, _ = precision_recall_fscore_support(
            labels, preds, average="binary", zero_division=0
        )

        print(f"Accuracy : {acc:.4f}")
        print(f"Precision : {precision:.4f}")
        print(f"Recall    : {recall:.4f}")
        print(f"F1 Score  : {f1:.4f}")
        print("\nClassification Report:")
        print(classification_report(labels, preds, zero_division=0))

        new_results.append({
            "Model": model_name,
            "Accuracy": acc,
            "Precision": precision,
            "Recall": recall,
            "F1 Score": f1
        })
    else:
        print("No labels found in new test data. Showing predictions only.")
        print("Predictions:", preds[:20])

# ---------------------------------------------------
# 8. NEW DATA COMPARISON TABLE
# ---------------------------------------------------
if new_results:
    new_results_df = pd.DataFrame(new_results)
    print("\n=========== RESULTS ON NEW TEST DATA ===========\n")
    print(new_results_df.sort_values(by="Accuracy", ascending=False))

New test columns: Index(['article', 'label'], dtype='str')

========== Testing DistilBERT on NEW data ==========

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

Accuracy : 0.5000
Precision : 0.0000
Recall    : 0.0000
F1 Score  : 0.0000

Classification Report:
              precision    recall  f1-score   support

           0       0.50      1.00      0.67        30
           1       0.00      0.00      0.00        30

    accuracy                           0.50        60
   macro avg       0.25      0.50      0.33        60
weighted avg       0.25      0.50      0.33        60


========== Testing BERT on NEW data ==========

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

Accuracy : 0.5000
Precision : 0.0000
Recall    : 0.0000
F1 Score  : 0.0000

Classification Report:
              precision    recall  f1-score   support

           0       0.50      1.00      0.67        30
           1       0.00      0.00      0.00        30

    accuracy                           0.50        60
   macro avg       0.25      0.50      0.33        60
weighted avg       0.25      0.50      0.33        60


========== Testing RoBERTa on NEW data ==========

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

Accuracy : 0.5000
Precision : 0.5000
Recall    : 1.0000
F1 Score  : 0.6667

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.50      1.00      0.67        30

    accuracy                           0.50        60
   macro avg       0.25      0.50      0.33        60
weighted avg       0.25      0.50      0.33        60


========== Testing ALBERT on NEW data ==========

Loading weights:   0%|          | 0/27 [00:00<?, ?it/s]

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

Accuracy : 0.4833
Precision : 0.4915
Recall    : 0.9667
F1 Score  : 0.6517

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.49      0.97      0.65        30

    accuracy                           0.48        60
   macro avg       0.25      0.48      0.33        60
weighted avg       0.25      0.48      0.33        60


=========== RESULTS ON NEW TEST DATA ===========

        Model  Accuracy  Precision    Recall  F1 Score
0  DistilBERT  0.500000   0.000000  0.000000  0.000000
1        BERT  0.500000   0.000000  0.000000  0.000000
2     RoBERTa  0.500000   0.500000  1.000000  0.666667
3      ALBERT  0.483333   0.491525  0.966667  0.651685

In [ ]:
print("Actual labels:")
print(pd.Series(labels).value_counts())

print("Predicted labels:")
print(pd.Series(preds).value_counts())